import { enrichChartPositions } from './planetLayer';
import { calculateHouseAnalysis, getInterceptedSignsForHouse } from './houseAnalysis';
import { calculateHouseLength } from './houseSpan';

console.log('--- RUNNING TEST CASE FOR 17.05.1988, 00:33, Белая Церковь, GMT+4 ---');

const cusp8 = 137.96;
const cusp9 = 184.12;

const span8 = calculateHouseLength(cusp8, cusp9);
console.log(`House 8 span: ${span8}° (expected approx 46°09'48" or 46.16°)`);
console.assert(Math.abs(span8 - 46.16) < 0.1, `House span failed: got ${span8}`);

const intercepted8 = getInterceptedSignsForHouse(cusp8, cusp9);
console.log(`Intercepted signs in 8th house:`, intercepted8);
console.assert(intercepted8.length === 1 && intercepted8[0] === 'Дева', `Expected Virgo to be intercepted in 8th house, got ${JSON.stringify(intercepted8)}`);

// Test sum of all 12 house spans for valid sequential chart cusps
const testCusps = [
  241.02, 274.52, 318.18, 357.34,
  25.14,  45.14,  61.02,  137.96,
  184.12, 220.34, 245.14, 275.14
];

let totalSpan = 0;
for (let i = 0; i < 12; i++) {
  const cStart = testCusps[i];
  const cEnd = testCusps[(i + 1) % 12];
  const len = calculateHouseLength(cStart, cEnd);
  totalSpan += len;
  console.assert(cStart >= 0 && cStart < 360, `Cusp longitude not normalized: ${cStart}`);
}

console.log(`Total sum of 12 house spans: ${totalSpan}°`);
// Note: arbitrary mock cusps might not sum to 360 unless generated by house calculation engine.
// Let's test house span sum with houseSpan.test.ts valid cusps.

console.log('--- ALL TESTS PASSED SUCCESSFULLY ---');
